version: '3.3'
services:
  perry:
    image: cwds/perry:3.0.3_786-RC
    hostname: perry
    restart: on-failure
    ports:
       - ${PERRY_PORT}:8080
       - ${PERRY_ADMIN_PORT}:8092
    env_file: .env

  dora:
    image: cwds/dora:latest
    command: bash -c "./entrypoint.sh 2>&1 | tee 'log.file'"
    depends_on:
      - perry
      - elasticsearch
    ports:
      - ${DORA_PORT}:8080
    restart: on-failure
    expose:
      - 8080
    env_file: .env
    healthcheck:
      test: head -n 500 log.file | grep "Started @"
      interval: 5s
      timeout: 10s
      retries: 80

  elasticsearch:
    image: cwds/elasticsearch_xpack_data:${ELASTICSEARCH_XPACK_DATA_VERSION}
    depends_on:
      - perry
    expose:
      - 9200
      - 9300
    env_file: .env
