version: "2"
services:
  elasticsearch_xpack_data:
    image: cwds/elasticsearch_xpack_data:latest
    restart: always
    volumes:
      - ./jvm.options:/usr/share/elasticsearch/config/jvm.options
#    environment:
#      - ES_JAVA_OPTS="-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9300:9300"
