applicationName: CWDS Dora

shiro:
  iniConfigs: ["file:${SHIRO_CONFIG_PATH:-config/shiro_v2.ini}"]
  
swagger:
  templateName: swagger.mustache
  assetsPath: /static
  resourcePackage: gov.ca.cwds.rest.resources
  title: CWDS Dora
  description: RESTful search services for the CWS New System.
  logo: images/CWDS-API-Logo-Horizontal.png
  loginUrl: ${PERRY_URL:-http://localhost:8080/perry/authn/login}
  logoutUrl: ${LOGOUT_URL:-http://localhost:8080/perry/authn/logout}
  spId: ${SP_ID:-} # service provider ID for Identity Mapping (defines security attributes for specific application)
  showSwagger: ${SHOW_SWAGGER:-true}
  jsonUrl: ${SWAGGER_JSON_URL:-http://localhost:8090/swagger.json}
  callbackUrl: ${SWAGGER_CALLBACK_URL:-http://localhost:8090/swagger}
  tokenUrl: ${SWAGGER_TOKEN_URL:-http://localhost:8080/perry/authn/token}

elasticsearch:
  nodes: ${ES_NODES:-dora.dev.cwds.io:9200,localhost:9210}
  user: ${XPACK_USER:-elastic}
  password: ${XPACK_PASSWORD:-changeme}
  responseFieldFilters:
    person: 'config/filters/person_filter.groovy'
  xpack:
    enabled: ${XPACK_ENABLED:-true}

server:
  applicationConnectors:
  - type: http 
    port: ${APP_STD_PORT:-8080}
  adminConnectors:
  - type: http
    port: ${APP_ADMIN_PORT:-8081}
    
  requestLog:
    appenders:
      - type: console

logging:
  level: ${LOGLEVEL:-INFO}
  loggers:
    "gov.ca.cwds":
      level: INFO
  appenders:
    - type: console
      threshold: INFO
      timeZone: UTC
      target: stdout
      logFormat: '[%X{UNIQUE_ID}] %X{remoteAddress} [%date{ISO8601}] %level "[%X{REQUEST_ID}]" %logger: "%message%n"'

version: -UNUSED-
